image: gitpod/workspace-full
ports:
- port: 3000
  onOpen: open-preview
tasks:
- init: >
    pyenv install 3.7.7 &&
    pyenv global 3.7.7 &&
    pip3 install --upgrade pip &&
    pip3 install pipenv &&
    pipenv install
  command: >
    export FLASK_APP=awesome-manager.py &&
    flask run
github:
    prebuilds:
        pullRequestsFromForks: true
